<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl"
                xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
                xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
>
    <xsl:output method="text" indent="yes"/>
    <xsl:template match="@* | node()">
% LaTeX code generated by SG pptx2beamer tool
\documentclass[first,firstsupp,navigation]{SG-ETHclass}
\usepackage{etex}
\setbeameroption{hide notes}
\setbeamertemplate{note page}{\ \\[.3cm]
\textbf{\color{c-bf}Notes:}\\
{\footnotesize
\insertnote}}
\setbeamertemplate{navigation symbols}{}

% some package definitions
\usepackage{pst-pdf,pst-all}
\usepackage{amsmath, amssymb}
\usepackage{pifont}
\usepackage{multimedia}

% some definitions
\newcommand{\Prob}{\mathrm{Pr}}
\newcommand{\sign}{\mathrm{sign}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\nbin}[1]{\mathrm{nb}_\mathrm{in}(#1)}
\newcommand{\nbout}[1]{\mathrm{nb}_\mathrm{out}(#1)}
\newcommand{\one}{\mathbb{\bf 1}}
\newcommand{\sref}[1]{SLIDE \ref{#1}}

% title and header
\title{<xsl:value-of select="//p:ph[@type='ctrTitle']/../../../p:txBody" />}
\author{Ingo Scholtes}
\newcommand{\shorttitle}{}
\newcommand{\homepage}{http://www.sg.ethz.ch}
\newcommand{\collaborators}{}
\newcommand{\event}{Complex Networks Lecture}
\newcommand{\place}{ETH Zurich}

% actual content starts here
% \end{document} will be added automatically after last slide

\begin{document}
  \frame{
    \maketitle
  }
    </xsl:template>
</xsl:stylesheet>
